name: MSBuild

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./serverextension
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

#permissions:
#  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - id: get-PATCH
      env:
          RUN_NUMB: ${{ github.run_number }}
      run: |
        echo "::set-output name=PATCH::$(echo $(($env:RUN_NUMB % 1000)) )"
    - name: GET PATCH version
      run: |
        echo "${{steps.get-PATCH.outputs.PATCH}}"
        
    - id: get-MINOR
      env:
          RUN_NUMB: ${{ github.run_number }}
      run: |
        echo "::set-output name=MINOR::$(echo $((($env:RUN_NUMB % 100000)-(($env:RUN_NUMB % 1000)))/1000) )"
    - name: GET MINOR version
      run: |
        echo "${{steps.get-MINOR.outputs.MINOR}}"
    - id: get-MAJOR
      env:
          RUN_NUMB: ${{ github.run_number }}
      run: |
        echo "::set-output name=MAJOR::$(echo $((($env:RUN_NUMB)-(($env:RUN_NUMB % 100000)))/100000) )"
    - name: GET MAJOR version
      run: |
        echo "${{steps.get-MAJOR.outputs.MAJOR}}"  
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: release-v${{steps.get-MAJOR.outputs.MAJOR}}.${{steps.get-Minor.outputs.Minor}}.${{steps.get-PATCH.outputs.PATCH}}
          release_name: Release v${{steps.get-MAJOR.outputs.MAJOR}}.${{steps.get-Minor.outputs.Minor}}.${{steps.get-PATCH.outputs.PATCH}}
    - name: Upload binary
      uses: actions/upload-release-asset@v1.0.1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: serverextension\Release\ServerExtention.dll
          asset_name: ServerExtention.dll
          asset_content_type: application/vnd.microsoft.portable-executable
